<?php

/**
 * Implements hook_permission().
 */
function etype_smugmug_permission() {
    return [
        'administer etype smugmug' => [
            'title' => t('Administer eType SmugMug'),
        ],
    ];
}

/**
 * @return array
 */
function etype_smugmug_menu() {

    $items['admin/config/etype/etype_smugmug/settings'] = [
        'title' => 'SmugMug Settings',
        'description' => 'Enter SmugMug settings.',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['etype_smugmug_admin_form'],
        'access arguments' => ['administer etype smugmug'],
        'file' => 'etype_smugmug.admin.inc',
        'type' => MENU_NORMAL_ITEM,
    ];

    return $items;
}

/**
 * Implements hook_block_info().
 */
function etype_smugmug_block_info() {
  $blocks = [];

  $blocks['smugmug'] = [
    'info' => t('SmugMug Photos'),
  ];
  
  return $blocks;
}

/**
 * @param string $delta
 * @return array
 * Implements hook_block_view().
 */
function etype_smugmug_block_view($delta = '') {
  $block = [];
  switch ($delta) {

    case 'smugmug':
      $block['subject'] = variable_get('etype_smugmug_blocktitle', 'Recent Photos');
      $block['content'] = _etype_smugmug_content();
      break;
    
  }
  return $block;
}

/**
 * Smugmug Block
 * @return null
 */
function _etype_smugmug_content() {

    drupal_add_css(drupal_get_path('module', 'etype_smugmug') . '/css/etype_smugmug.css', array(
        'group' => CSS_THEME,
        'type' => 'file'
    ));

    $user_name = variable_get('etype_smugmug_user');
    $api_key = variable_get('etype_smugmug_apikey');
    $app_name = variable_get('etype_smugmug_appname');

    require_once '/mnt/data/web/vendor/autoload.php';
    $output = '<div id="smugmug_div">';

    try {

        $options = [
            'AppName' => $app_name,
            '_verbosity' => 1
        ];

        $client = new phpSmug\Client($api_key, $options);
        $albums = $client->get("user/{$user_name}!albums", array('count' => 1));
        $images = $client->get($albums->Album[0]->Uris->AlbumImages, array('count' => 9));
        foreach ($images->AlbumImage as $image) {
            $output .= sprintf('<a href="%s" target="_blank"><img src="%s" title="%s" alt="%s" width="150"  class="smugmug_thumb" /></a>', $image->WebUri, $image->ThumbnailUrl, $image->Title, $image->ImageKey);
        }

        /*
        if (count($albums) > 0) {
            $tmp = $albums->Album[0]->Uris->AlbumImages;
            if (count($tmp) == 0) {
                $tmp = $albums->Album[1]->Uris->AlbumImages;
            }
            if (count($tmp) > 0) {
                $images = $client->get($tmp, array('count' => 25));
                foreach ($images->AlbumImage as $image) {
                    var_dump($image);
                    //$output .= sprintf('<a href="%s" target="_blank"><img src="%s" title="%s" alt="%s" width="150"  class="smugmug_thumb" /></a>', $image->WebUri, $image->ThumbnailUrl, $image->Title, $image->ImageKey);
                }
            } else {
                $output .= 'No SmugMug images found.';
            }
        } else {
            $output .= 'No SmugMug albums found.';
        }*/

    } catch (Exception $e) {
        $output .= sprintf('%s (Error Code: %d)', $e->getMessage(), $e->getCode());
    }

    $output .= '</div>';
    return $output;
}
